name: Build and analyze on SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build and analyze on SonarCloud
        working-directory: modernos
        run: |
          npm install
          npx sonar-scanner \
            -Dsonar.projectKey=valeriavcgr_AplicacionCalidad \
            -Dsonar.organization=valeriavcgr \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
